export interface ImageRecord {
  key: string;
  title: string;
  caption: string | null;
  original_filename: string;
  public_url: string;
  width: number;
  height: number;
  format: string;
  bytes_compressed: number;
  original_bytes: number | null;
  original_width: number | null;
  original_height: number | null;
  location_name: string | null;
  location_lat: number | null;
  location_lng: number | null;
  location_region: string | null;
  exif_taken_at: string | null;
  exif_camera: string | null;
  exif_iso: number | null;
  exif_aperture: number | null;
  exif_shutter: string | null;
  exif_focal_length: number | null;
  tags_json: string | null;
  search_content?: string | null;
  dominant_color: string | null;
  color_palette_json: string | null;
  composition: string | null;
  ai_status: string;
  tg_status: string;
  created_at: string;
  updated_at: string;
  is_public: number;
  location_public: number;
  folder_id: string | null;
}
